# Generated by Django 5.2.18 on 2026-10-07 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='langitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
    ]
