# Generated by Django 5.2.18 on 2026-10-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location_langitude_location_latitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='langitude',
            new_name='longitude',
        ),
    ]
